### ISSUE TITLE
Starting DeepStack Windows Beta fails

### ISSUE THREAD

**Issue by edalquist** [VorlonCD/bi-aidetection#111]
I've installed the DeepStack windows beta. Everything works as expected when I manually start DeepStack via:

```
C:\DeepStack>deepstack.exe -VISION-DETECTION=True
```

But if I use the DeepStack tab in AITool 2.0.37.706 I get the following error in the log when trying to start DeepStack:

```
2020-12-23 09:30:23.190548|Error|AITOOLS.EXE|DSHandleInitProcERROR|None|PYTHON.EXE|None|    Debug: DeepStack>> Init:  Traceback (most recent call last):|46|4||12
2020-12-23 09:30:23.208546|Error|AITOOLS.EXE|DSHandleInitProcERROR|None|PYTHON.EXE|None|    Debug: DeepStack>> Init:    File "../init.py", line 9, in <module>|51|4||12
2020-12-23 09:30:23.209550|Error|AITOOLS.EXE|DSHandleInitProcERROR|None|PYTHON.EXE|None|    Debug: DeepStack>> Init:      conn = sqlite3.connect(DATA_DIR + "/faceembedding.db")|52|4||12
2020-12-23 09:30:23.210550|Error|AITOOLS.EXE|DSHandleInitProcERROR|None|PYTHON.EXE|None|    Debug: DeepStack>> Init:  sqlite3.Operational unable to open database file|53|4||12
2020-12-23 09:30:23.337548|Warn|AITOOLS.EXE|DSHandleRedisProcMSG|None|PYTHON.EXE|REDIS-SERVER.EXE|  Debug: DeepStack>> [10584] 23 Dec 09:30:23 #  no config file specified, using the default config. In order to specify a config file use 'redis-server /path/to/redis.conf'|58|2||5
2020-12-23 09:30:23.386547|Error|AITOOLS.EXE|Start|None|PYTHON.EXE|None|   Cannot start: Object reference not set to an instance of an object. [NullReferenceException] Mod: <Start>d__28 Line:335:21|60|2||10
2020-12-23 09:30:23.944550|Error|AITOOLS.EXE|Start|None|PYTHON.EXE|None|  Cannot start: The system cannot find the file specified [Win32Exception] Mod: <Start>d__28 Line:357:17|61|1||8
2020-12-23 09:30:23.945559|Error|AITOOLS.EXE|DSHandleInitProcERROR|None|PYTHON.EXE|None|Debug: DeepStack>> Init:  Traceback (most recent call last):|62|0||12
2020-12-23 09:30:23.946549|Error|AITOOLS.EXE|DSHandleInitProcERROR|None|PYTHON.EXE|None|Debug: DeepStack>> Init:    File "../init.py", line 9, in <module>|67|0||12
2020-12-23 09:30:23.947547|Error|AITOOLS.EXE|DSHandleInitProcERROR|None|PYTHON.EXE|None|Debug: DeepStack>> Init:      conn = sqlite3.connect(DATA_DIR + "/faceembedding.db")|68|0||12
2020-12-23 09:30:23.949555|Error|AITOOLS.EXE|DSHandleInitProcERROR|None|PYTHON.EXE|None|Debug: DeepStack>> Init:  sqlite3.Operational unable to open database file|69|0||12
```

**Comment by VorlonCD** [comment]
The latest I posed in the "Future of deepquest" issue thread now has support for the new beta

[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5736965/AITOOL-VORLONCD.zip)
