### ISSUE TITLE
View Image from History - Windows11

### ISSUE THREAD

**Issue by Yonny24** [VorlonCD/bi-aidetection#292]
Hi, 
I'm wondering how I can solve this AI tool unhandled exception error now when I click on 'View image'. 

Worked fine on Windows 10 until I upgraded yesterday. I'm assuming it's trying to open a program that is not associated anymore.

What suggestions do you have to fix this?

many thanks

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): No application is associated with the specified file for this operation
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at AITool.Shell.viewImageToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Documents\Projects\_GIT\VorlonCD\bi-aidetection\src\UI\Shell.cs:line 5341
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)`

**Comment by VorlonCD** [comment]
I can replicate, even outside of AITOOL.   Bad Windows 11, BAD!  Go sit in the corner.  If I tell JPG files to always open with PHOTOS that error pops up when I open a jpg.

But when I tell JPG files to always open with a 3rd party tool such as **IrfanView**, it works?   Not sure why.
